### ISSUE TITLE
venv instructions are missing from README

### ISSUE THREAD

**Issue by Akuli** [adder32/venom#3]
Someone not familiar with Python would probably have trouble running tests. The README only tells you to do `make test`, and you get:

```
akuli@akuli-desktop:~/venom$ make test
Error: Virtual environment is not active. Activate it using 'source <your_env>/bin/activate' and then run 'make test'
make: *** [Makefile:83: test] Error 1
```

This error message is good, but it makes sense only if you are familiar with Python and its virtualenvs.

**Comment by adder32** [comment]
I'll fix the instructions.
